import{TARGET_CURVE_OPTIONS,formatHz,esc}from"./ui-utils.js?v=0.6.1";

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const logX=(f,left=48,width=682)=>left+(Math.log10(clamp(f,20,20000))-Math.log10(20))/(Math.log10(20000)-Math.log10(20))*width;
const gainY=(g,top=34,height=238)=>top+(12-clamp(g,-12,12))/24*height;
const samples=Array.from({length:121},(_,i)=>20*Math.pow(1000,i/120));

function bellValue(f,band){if(!band.enabled||Math.abs(band.gain)<.001)return 0;const oct=Math.log2(f/Math.max(20,band.frequency)),width=Math.max(.035,1/(Math.max(.1,band.q)*1.5));return band.gain*Math.exp(-.5*Math.pow(oct/width,2))}
function eqValue(channel,f){return channel.eqBands.reduce((sum,band)=>sum+bellValue(f,band),0)}
function targetValue(points,f){if(!points?.length)return 0;const sorted=[...points].sort((a,b)=>Number(a.frequency_hz)-Number(b.frequency_hz));if(f<=Number(sorted[0].frequency_hz))return Number(sorted[0].gain_db)||0;if(f>=Number(sorted.at(-1).frequency_hz))return Number(sorted.at(-1).gain_db)||0;for(let i=0;i<sorted.length-1;i++){const a=sorted[i],b=sorted[i+1],fa=Number(a.frequency_hz),fb=Number(b.frequency_hz);if(f>=fa&&f<=fb){const t=(Math.log(f)-Math.log(fa))/(Math.log(fb)-Math.log(fa));return(Number(a.gain_db)||0)+((Number(b.gain_db)||0)-(Number(a.gain_db)||0))*t}}return 0}
function pathFor(fn){return samples.map((f,i)=>`${i?"L":"M"}${logX(f).toFixed(1)},${gainY(fn(f)).toFixed(1)}`).join(" ")}

function eqGraph(channel,target){const eqPath=pathFor(f=>eqValue(channel,f)),targetPath=pathFor(f=>targetValue(target?.points||[],f));const xTicks=[20,50,100,200,500,1000,2000,5000,10000,20000],yTicks=[12,6,0,-6,-12];return`<svg class="eq-graph" viewBox="0 0 780 320" role="img" aria-label="Electrical EQ and target curve preview"><rect x="48" y="34" width="682" height="238" rx="8"/><g class="eq-grid">${yTicks.map(g=>`<line x1="48" y1="${gainY(g)}" x2="730" y2="${gainY(g)}"/><text x="10" y="${gainY(g)+4}">${g>0?"+":""}${g}</text>`).join("")}${xTicks.map(f=>`<line x1="${logX(f)}" y1="34" x2="${logX(f)}" y2="272"/><text x="${logX(f)}" y="296" text-anchor="middle">${formatHz(f)}</text>`).join("")}</g><line class="eq-zero" x1="48" y1="${gainY(0)}" x2="730" y2="${gainY(0)}"/><path class="target-path" d="${targetPath}"/><path class="eq-path" style="--ch:${channel.color}" d="${eqPath}"/>${channel.eqBands.filter(b=>b.enabled).map(b=>`<circle class="eq-point" style="--ch:${channel.color}" cx="${logX(b.frequency)}" cy="${gainY(eqValue(channel,b.frequency))}" r="3.5"/>`).join("")}<text class="axis-label" x="390" y="316" text-anchor="middle">Frequency</text></svg>`}

function channelTabs(ch,current){return`<div class="eq-channel-tabs">${ch.map(c=>`<button class="${c.index===current?"active":""}" style="--ch:${c.color}" data-action="eq-channel" data-index="${c.index}"><i></i><b>${esc(c.output)}</b><span>${esc(c.speaker)}</span><small>${c.eqActiveBands} active</small></button>`).join("")}</div>`}
function bandRail(channel,selected){return`<div class="eq-band-rail">${channel.eqBands.map(b=>`<button class="${b.index===selected?"active":""} ${b.enabled?"enabled":""}" style="--gain:${clamp((b.gain+12)/24*100,0,100)}%;--ch:${channel.color}" data-action="eq-band" data-band="${b.index}"><b>${b.index+1}</b><span>${formatHz(b.frequency)}</span><small>${b.gain>0?"+":""}${b.gain.toFixed(1)}</small></button>`).join("")}</div>`}
function numberInput(label,field,value,unit,min,max,step,dec){return`<label class="eq-field"><span>${label}</span><div><input data-eq-number data-field="${field}" type="number" min="${min}" max="${max}" step="${step}" value="${Number(value).toFixed(dec)}"><b>${unit}</b></div></label>`}
function bandEditor(channel,band){return`<div class="card eq-editor"><div class="eq-editor-head"><div><small>SELECTED BAND</small><h3>Band ${band.index+1} · ${formatHz(band.frequency)}</h3></div><button class="eq-enable ${band.enabled?"on":""}" data-action="eq-toggle">${band.enabled?"Enabled":"Disabled"}</button></div>${numberInput("Frequency","frequency_hz",band.frequency,"Hz",20,20000,.1,1)}${numberInput("Gain","gain_db",band.gain,"dB",-12,12,.1,1)}${numberInput("Q","q",band.q,"",.1,20,.01,2)}<div class="eq-band-note"><b>PEQ preview</b><span>SoundLab models this band as a peaking filter for visual tuning. Final acoustic correction should be based on measurement.</span></div></div>`}

function rewCurveData(target){return[...(target?.points||[])].map(p=>({frequency:Number(p.frequency_hz),gain:Number(p.gain_db)||0})).filter(p=>Number.isFinite(p.frequency)&&Number.isFinite(p.gain)).sort((a,b)=>a.frequency-b.frequency).map(p=>`${Number.isInteger(p.frequency)?p.frequency:p.frequency.toFixed(1)} ${p.gain.toFixed(2)}`).join("\n")+"\n"}
function houseGraph(points,selected){const xTicks=[20,50,100,200,500,1000,2000,5000,10000,20000],yTicks=[12,6,0,-6,-12],curve=pathFor(f=>targetValue(points,f));return`<svg class="house-graph" viewBox="0 0 780 310" role="img" aria-label="House Curve editor"><rect x="48" y="34" width="682" height="238" rx="8"/><g class="eq-grid">${yTicks.map(g=>`<line x1="48" y1="${gainY(g)}" x2="730" y2="${gainY(g)}"/><text x="10" y="${gainY(g)+4}">${g>0?"+":""}${g}</text>`).join("")}${xTicks.map(f=>`<line x1="${logX(f)}" y1="34" x2="${logX(f)}" y2="272"/><text x="${logX(f)}" y="296" text-anchor="middle">${formatHz(f)}</text>`).join("")}</g><line class="eq-zero" x1="48" y1="${gainY(0)}" x2="730" y2="${gainY(0)}"/><path class="house-path" d="${curve}"/>${points.map((point,i)=>`<circle class="house-node ${i===selected?"selected":""}" data-house-action="select" data-index="${i}" cx="${logX(Number(point.frequency_hz))}" cy="${gainY(Number(point.gain_db))}" r="${i===selected?7:5}"/>`).join("")}</svg>`}

class KCCHouseCurveEditor0615 extends HTMLElement{
 connectedCallback(){if(this._bound)return;this._bound=true;this.addEventListener("click",e=>this.onClick(e));this.addEventListener("change",e=>this.onChange(e));this.render()}
 panel(){return this.getRootNode()?.host||null}
 target(){return this.panel()?.workspace?.target_curve||{preset:"Flat",points:[]}}
 points(){return[...(this.target().points||[])].map(p=>({frequency_hz:Number(p.frequency_hz),gain_db:Number(p.gain_db)||0})).filter(p=>Number.isFinite(p.frequency_hz)&&Number.isFinite(p.gain_db)).sort((a,b)=>a.frequency_hz-b.frequency_hz)}
 selected(points=this.points()){const p=this.panel();let index=Number(p?.houseCurvePoint);if(!Number.isInteger(index)||index<0||index>=points.length)index=0;if(p)p.houseCurvePoint=index;return index}
 async save(points,preferredFrequency){const p=this.panel();if(!p?.send)return;try{p.workspace=await p.send("kcc_soundlab/set_target_curve_points",{points});p.error="";const saved=[...(p.workspace?.target_curve?.points||[])].sort((a,b)=>Number(a.frequency_hz)-Number(b.frequency_hz));if(saved.length){let best=0;if(Number.isFinite(Number(preferredFrequency))){let delta=Infinity;saved.forEach((point,i)=>{const d=Math.abs(Math.log(Number(point.frequency_hz))-Math.log(Number(preferredFrequency)));if(d<delta){delta=d;best=i}})}p.houseCurvePoint=best}else p.houseCurvePoint=0}catch(err){p.error=String(err?.message||err)}p.render()}
 async addPoint(){const points=this.points();if(points.length>=16)return;let slot=0,gap=-Infinity;for(let i=0;i<points.length-1;i++){const current=Math.log(points[i+1].frequency_hz/points[i].frequency_hz);if(current>gap){gap=current;slot=i}}const a=points[slot],b=points[Math.min(slot+1,points.length-1)];let frequency=a&&b&&a!==b?Math.sqrt(a.frequency_hz*b.frequency_hz):1000;frequency=Math.round(frequency*10)/10;while(points.some(point=>Math.abs(point.frequency_hz-frequency)<.001)&&frequency<20000)frequency=Math.round((frequency+.1)*10)/10;const gain=a&&b&&a!==b?(a.gain_db+b.gain_db)/2:0;points.push({frequency_hz:frequency,gain_db:Math.round(gain*10)/10});await this.save(points,frequency)}
 async removePoint(){const points=this.points(),index=this.selected(points);if(points.length<=2)return;const fallback=points[Math.max(0,index-1)]?.frequency_hz??points[0]?.frequency_hz;points.splice(index,1);await this.save(points,fallback)}
 onClick(e){const control=e.target.closest("[data-house-action]");if(!control)return;const action=control.dataset.houseAction;if(action==="select"){const p=this.panel();if(p)p.houseCurvePoint=Number(control.dataset.index)||0;this.render()}else if(action==="add")this.addPoint();else if(action==="remove")this.removePoint()}
 onChange(e){const input=e.target.closest("[data-house-field]");if(!input)return;const points=this.points(),index=this.selected(points),field=input.dataset.houseField,value=Number(input.value);if(!points[index]||!Number.isFinite(value))return;if(field==="frequency_hz"){const frequency=clamp(value,20,20000);if(points.some((point,i)=>i!==index&&Math.abs(point.frequency_hz-frequency)<.001)){const p=this.panel();if(p){p.error="House Curve frequencies must be unique";p.render()}return}points[index].frequency_hz=frequency;this.save(points,frequency)}else if(field==="gain_db"){points[index].gain_db=clamp(value,-12,12);this.save(points,points[index].frequency_hz)}}
 render(){const p=this.panel(),target=this.target(),points=this.points(),selected=this.selected(points),point=points[selected]||{frequency_hz:20,gain_db:0},options=p?.workspace?.eq?.target_curve_options||TARGET_CURVE_OPTIONS,rewData=rewCurveData({points}),rewHref=`data:text/plain;charset=utf-8,${encodeURIComponent(rewData)}`,filePreset=String(target.preset||"Custom").replace(/[^a-z0-9]+/gi,"_").replace(/^_+|_+$/g,"")||"Custom";this.innerHTML=`<div class="card target-card house-editor"><div class="target-head"><div><small>HOUSE CURVE LAB · GRAPH EDITOR · REW EXPORT</small><h3>${esc(target.preset||"Flat")}</h3></div><select data-target-preset>${options.map(x=>`<option ${x===target.preset?"selected":""}>${esc(x)}</option>`).join("")}</select></div>${houseGraph(points,selected)}<div class="house-toolbar"><div><strong>${points.length}/16 points</strong><span>Click a node or point below to edit it</span></div><button data-house-action="add" ${points.length>=16?"disabled":""}>+ Add point</button></div><div class="house-point-list">${points.map((item,i)=>`<button class="${i===selected?"active":""}" data-house-action="select" data-index="${i}"><b>${formatHz(item.frequency_hz)}</b><span>${item.gain_db>=0?"+":""}${item.gain_db.toFixed(1)} dB</span></button>`).join("")}</div><div class="house-edit-grid"><label><span>Selected frequency</span><div><input data-house-field="frequency_hz" type="number" min="20" max="20000" step="0.1" value="${Number(point.frequency_hz).toFixed(1)}"><b>Hz</b></div></label><label><span>Selected offset</span><div><input data-house-field="gain_db" type="number" min="-12" max="12" step="0.1" value="${Number(point.gain_db).toFixed(1)}"><b>dB</b></div></label><button class="danger" data-house-action="remove" ${points.length<=2?"disabled":""}>Remove point</button></div><div class="house-export"><a href="${rewHref}" download="KCC_House_Curve_${filePreset}.txt" target="_blank" rel="noopener">Download for REW (.txt)</a><span>${points.length} ascending Hz / dB offset points · logarithmic interpolation</span></div><p>The graph and REW file use the same persistent House Curve points as the EQ target overlay. Add, remove or move points between 20 Hz and 20 kHz. House Curve editing never changes channel EQ or DSP values automatically.</p></div>`}
}
customElements.get("kcc-house-curve-editor-0615")||customElements.define("kcc-house-curve-editor-0615",KCCHouseCurveEditor0615);

function toolsCard(p,ch,channel){const current=channel.index;let target=Number(p.eqCopyTarget);if(!Number.isInteger(target)||target<0||target>=ch.length||target===current)target=ch.find(c=>c.index!==current)?.index??current;p.eqCopyTarget=target;const gains=channel.eqBands.filter(b=>b.enabled).map(b=>b.gain),boost=gains.length?Math.max(0,...gains):0,cut=gains.length?Math.min(0,...gains):0;return`<div class="card eq-tools"><h3>CHANNEL EQ TOOLS</h3><div class="eq-stats"><div><small>ACTIVE BANDS</small><strong>${channel.eqActiveBands}/31</strong></div><div><small>MAX BOOST</small><strong class="amber">+${boost.toFixed(1)} dB</strong></div><div><small>MAX CUT</small><strong>${cut.toFixed(1)} dB</strong></div></div><label class="eq-copy"><span>Copy ${esc(channel.output)} EQ to</span><select data-eq-copy-target>${ch.filter(c=>c.index!==current).map(c=>`<option value="${c.index}" ${c.index===target?"selected":""}>${esc(c.output)} · ${esc(c.speaker)}</option>`).join("")}</select></label><div class="eq-tool-actions"><button data-action="eq-copy">Copy EQ</button><button class="danger" data-action="eq-reset">Reset channel EQ</button></div>${boost>3?`<div class="eq-warning"><b>Headroom reminder</b><span>Large positive EQ boosts can reduce digital headroom. Prefer cuts where practical and verify level after tuning.</span></div>`:""}</div>`}

export function eqView(p,ch){if(!ch.length)return`<div class="card empty-state">No active outputs.</div>`;let channelIndex=Number(p.eqChannel);if(!Number.isInteger(channelIndex)||channelIndex<0||channelIndex>=ch.length)channelIndex=0;p.eqChannel=channelIndex;const channel=ch[channelIndex];let bandIndex=Number(p.eqBand);if(!Number.isInteger(bandIndex)||bandIndex<0||bandIndex>=channel.eqBands.length)bandIndex=0;p.eqBand=bandIndex;const band=channel.eqBands[bandIndex],target=p.workspace?.target_curve||{points:[]};return`<section class="eq-workspace">${channelTabs(ch,channelIndex)}<div class="eq-top"><div class="card eq-main"><div class="eq-title"><div><small>31-BAND EQ · ${esc(channel.output)}</small><h2>${esc(channel.speaker)}</h2><span>${esc(channel.role)} · ${esc(channel.location)}</span></div><div class="eq-legend"><span><i class="eq-line" style="--ch:${channel.color}"></i>Electrical EQ preview</span><span><i class="target-line"></i>House Curve target</span></div></div>${eqGraph(channel,target)}${bandRail(channel,bandIndex)}</div>${bandEditor(channel,band)}</div><div class="eq-bottom"><kcc-house-curve-editor-0615></kcc-house-curve-editor-0615>${toolsCard(p,ch,channel)}<div class="card eq-guide"><h3>EQ WORKFLOW</h3><ol><li>Choose one output and start with all EQ bands flat.</li><li>Use Measurement Center later to identify repeatable peaks/dips.</li><li>Prefer correcting broad, repeatable problems rather than every narrow measurement feature.</li><li>Compare the electrical EQ preview with the House Curve target.</li><li>Save a tuning snapshot before major EQ changes.</li></ol><button data-action="view" data-view="measurement">Open Measurement Center</button></div></div></section>`}