import{TARGET_CURVE_OPTIONS,formatHz,esc}from"./ui-utils.js?v=0.6.1";

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const logX=(f,left=48,width=682)=>left+(Math.log10(clamp(f,20,20000))-Math.log10(20))/(Math.log10(20000)-Math.log10(20))*width;
const gainY=(g,top=34,height=238)=>top+(12-clamp(g,-12,12))/24*height;
const samples=Array.from({length:121},(_,i)=>20*Math.pow(1000,i/120));

function bellValue(f,band){if(!band.enabled||Math.abs(band.gain)<.001)return 0;const oct=Math.log2(f/Math.max(20,band.frequency)),width=Math.max(.035,1/(Math.max(.1,band.q)*1.5));return band.gain*Math.exp(-.5*Math.pow(oct/width,2))}
function eqValue(channel,f){return channel.eqBands.reduce((sum,band)=>sum+bellValue(f,band),0)}
function targetValue(points,f){if(!points?.length)return 0;const sorted=[...points].sort((a,b)=>Number(a.frequency_hz)-Number(b.frequency_hz));if(f<=Number(sorted[0].frequency_hz))return Number(sorted[0].gain_db)||0;if(f>=Number(sorted.at(-1).frequency_hz))return Number(sorted.at(-1).gain_db)||0;for(let i=0;i<sorted.length-1;i++){const a=sorted[i],b=sorted[i+1],fa=Number(a.frequency_hz),fb=Number(b.frequency_hz);if(f>=fa&&f<=fb){const t=(Math.log(f)-Math.log(fa))/(Math.log(fb)-Math.log(fa));return(Number(a.gain_db)||0)+((Number(b.gain_db)||0)-(Number(a.gain_db)||0))*t}}return 0}
function pathFor(fn){return samples.map((f,i)=>`${i?"L":"M"}${logX(f).toFixed(1)},${gainY(fn(f)).toFixed(1)}`).join(" ")}

function eqGraph(channel,target){const eqPath=pathFor(f=>eqValue(channel,f)),targetPath=pathFor(f=>targetValue(target?.points||[],f));const xTicks=[20,50,100,200,500,1000,2000,5000,10000,20000],yTicks=[12,6,0,-6,-12];return`<svg class="eq-graph" viewBox="0 0 780 320" role="img" aria-label="Electrical EQ and target curve preview"><rect x="48" y="34" width="682" height="238" rx="8"/><g class="eq-grid">${yTicks.map(g=>`<line x1="48" y1="${gainY(g)}" x2="730" y2="${gainY(g)}"/><text x="10" y="${gainY(g)+4}">${g>0?"+":""}${g}</text>`).join("")}${xTicks.map(f=>`<line x1="${logX(f)}" y1="34" x2="${logX(f)}" y2="272"/><text x="${logX(f)}" y="296" text-anchor="middle">${formatHz(f)}</text>`).join("")}</g><line class="eq-zero" x1="48" y1="${gainY(0)}" x2="730" y2="${gainY(0)}"/><path class="target-path" d="${targetPath}"/><path class="eq-path" style="--ch:${channel.color}" d="${eqPath}"/>${channel.eqBands.filter(b=>b.enabled).map(b=>`<circle class="eq-point" style="--ch:${channel.color}" cx="${logX(b.frequency)}" cy="${gainY(eqValue(channel,b.frequency))}" r="3.5"/>`).join("")}<text class="axis-label" x="390" y="316" text-anchor="middle">Frequency</text></svg>`}

function channelTabs(ch,current){return`<div class="eq-channel-tabs">${ch.map(c=>`<button class="${c.index===current?"active":""}" style="--ch:${c.color}" data-action="eq-channel" data-index="${c.index}"><i></i><b>${esc(c.output)}</b><span>${esc(c.speaker)}</span><small>${c.eqActiveBands} active</small></button>`).join("")}</div>`}
function bandRail(channel,selected){return`<div class="eq-band-rail">${channel.eqBands.map(b=>`<button class="${b.index===selected?"active":""} ${b.enabled?"enabled":""}" style="--gain:${clamp((b.gain+12)/24*100,0,100)}%;--ch:${channel.color}" data-action="eq-band" data-band="${b.index}"><b>${b.index+1}</b><span>${formatHz(b.frequency)}</span><small>${b.gain>0?"+":""}${b.gain.toFixed(1)}</small></button>`).join("")}</div>`}
function numberInput(label,field,value,unit,min,max,step,dec){return`<label class="eq-field"><span>${label}</span><div><input data-eq-number data-field="${field}" type="number" min="${min}" max="${max}" step="${step}" value="${Number(value).toFixed(dec)}"><b>${unit}</b></div></label>`}
function bandEditor(channel,band){return`<div class="card eq-editor"><div class="eq-editor-head"><div><small>SELECTED BAND</small><h3>Band ${band.index+1} · ${formatHz(band.frequency)}</h3></div><button class="eq-enable ${band.enabled?"on":""}" data-action="eq-toggle">${band.enabled?"Enabled":"Disabled"}</button></div>${numberInput("Frequency","frequency_hz",band.frequency,"Hz",20,20000,.1,1)}${numberInput("Gain","gain_db",band.gain,"dB",-12,12,.1,1)}${numberInput("Q","q",band.q,"",.1,20,.01,2)}<div class="eq-band-note"><b>PEQ preview</b><span>SoundLab models this band as a peaking filter for visual tuning. Final acoustic correction should be based on measurement.</span></div></div>`}
function targetCard(p){const target=p.workspace?.target_curve||{preset:"Flat",points:[]},options=p.workspace?.eq?.target_curve_options||TARGET_CURVE_OPTIONS;return`<div class="card target-card"><div class="target-head"><div><small>TARGET CURVE</small><h3>${esc(target.preset||"Flat")}</h3></div><select data-target-preset>${options.map(x=>`<option ${x===target.preset?"selected":""}>${esc(x)}</option>`).join("")}</select></div><div class="target-points">${(target.points||[]).map((point,i)=>`<label><span>${formatHz(Number(point.frequency_hz))}</span><div><input data-target-point data-point="${i}" type="number" min="-12" max="12" step="0.1" value="${Number(point.gain_db||0).toFixed(1)}"><b>dB</b></div></label>`).join("")}</div><p>Target curve is a reference overlay only. It does not change the channel EQ automatically.</p></div>`}
function toolsCard(p,ch,channel){const current=channel.index;let target=Number(p.eqCopyTarget);if(!Number.isInteger(target)||target<0||target>=ch.length||target===current)target=ch.find(c=>c.index!==current)?.index??current;p.eqCopyTarget=target;const gains=channel.eqBands.filter(b=>b.enabled).map(b=>b.gain),boost=gains.length?Math.max(0,...gains):0,cut=gains.length?Math.min(0,...gains):0;return`<div class="card eq-tools"><h3>CHANNEL EQ TOOLS</h3><div class="eq-stats"><div><small>ACTIVE BANDS</small><strong>${channel.eqActiveBands}/31</strong></div><div><small>MAX BOOST</small><strong class="amber">+${boost.toFixed(1)} dB</strong></div><div><small>MAX CUT</small><strong>${cut.toFixed(1)} dB</strong></div></div><label class="eq-copy"><span>Copy ${esc(channel.output)} EQ to</span><select data-eq-copy-target>${ch.filter(c=>c.index!==current).map(c=>`<option value="${c.index}" ${c.index===target?"selected":""}>${esc(c.output)} · ${esc(c.speaker)}</option>`).join("")}</select></label><div class="eq-tool-actions"><button data-action="eq-copy">Copy EQ</button><button class="danger" data-action="eq-reset">Reset channel EQ</button></div>${boost>3?`<div class="eq-warning"><b>Headroom reminder</b><span>Large positive EQ boosts can reduce digital headroom. Prefer cuts where practical and verify level after tuning.</span></div>`:""}</div>`}

export function eqView(p,ch){if(!ch.length)return`<div class="card empty-state">No active outputs.</div>`;let channelIndex=Number(p.eqChannel);if(!Number.isInteger(channelIndex)||channelIndex<0||channelIndex>=ch.length)channelIndex=0;p.eqChannel=channelIndex;const channel=ch[channelIndex];let bandIndex=Number(p.eqBand);if(!Number.isInteger(bandIndex)||bandIndex<0||bandIndex>=channel.eqBands.length)bandIndex=0;p.eqBand=bandIndex;const band=channel.eqBands[bandIndex],target=p.workspace?.target_curve||{points:[]};return`<section class="eq-workspace">${channelTabs(ch,channelIndex)}<div class="eq-top"><div class="card eq-main"><div class="eq-title"><div><small>31-BAND EQ · ${esc(channel.output)}</small><h2>${esc(channel.speaker)}</h2><span>${esc(channel.role)} · ${esc(channel.location)}</span></div><div class="eq-legend"><span><i class="eq-line" style="--ch:${channel.color}"></i>Electrical EQ preview</span><span><i class="target-line"></i>Target curve</span></div></div>${eqGraph(channel,target)}${bandRail(channel,bandIndex)}</div>${bandEditor(channel,band)}</div><div class="eq-bottom">${targetCard(p)}${toolsCard(p,ch,channel)}<div class="card eq-guide"><h3>EQ WORKFLOW</h3><ol><li>Choose one output and start with all EQ bands flat.</li><li>Use Measurement Center later to identify repeatable peaks/dips.</li><li>Prefer correcting broad, repeatable problems rather than every narrow measurement feature.</li><li>Compare the electrical EQ preview with the target reference.</li><li>Save a tuning snapshot before major EQ changes.</li></ol><button data-action="view" data-view="measurement">Open Measurement Center</button></div></div></section>`}